<?php

namespace Tests\Feature;

use App\Models\Order;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use SGCart\LogisticTracking\Models\OrderTracking;
use Tests\TestCase;

class LogisticTrackingTest extends TestCase
{
    use RefreshDatabase;

    protected User $admin;

    protected function setUp(): void
    {
        parent::setUp();

        // Create an admin user for authentication
        $this->admin = User::create([
            'name' => 'Admin User',
            'email' => 'admin_' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
        ]);

        $permission = \Spatie\Permission\Models\Permission::firstOrCreate(['name' => 'manage products', 'guard_name' => 'web']);
        $this->admin->givePermissionTo($permission);
    }

    /**
     * Test that order tracking can be saved manually.
     */
    public function test_order_tracking_can_be_saved_manually(): void
    {
        $order = Order::create([
            'ulid' => (string) \Illuminate\Support\Str::ulid(),
            'order_number' => 'ORD-' . rand(1000, 9999),
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
            'address' => '123 Main St',
            'city' => 'New York',
            'zip' => '10001',
            'subtotal' => 100.00,
            'tax' => 10.00,
            'total' => 110.00,
            'status' => 'Processing',
        ]);

        $courier = \SGCart\LogisticTracking\Models\ShippingCourier::create([
            'name' => 'DHL Express',
            'url' => 'https://dhl.com/track/{tracking_number}',
            'support_email' => 'support@dhl.com',
        ]);

        $response = $this->actingAs($this->admin)->put(route('admin.orders.update', $order->ulid), [
            'status' => 'Shipped',
            'payment_status' => 'Paid',
            'tracking_number' => 'TEST-12345',
            'shipping_courier_id' => $courier->id,
            'tracking_url' => null,
            'estimated_delivery_at' => '2026-07-05',
        ]);

        $response->assertSessionHasNoErrors();
        $response->assertRedirect();
        $this->assertDatabaseHas('order_trackings', [
            'order_id' => $order->id,
            'tracking_number' => 'TEST-12345',
            'shipping_courier_id' => $courier->id,
            'shipping_carrier' => 'DHL Express',
            'tracking_url' => 'https://dhl.com/track/TEST-12345',
        ]);

        $this->assertDatabaseHas('activity_log', [
            'event' => 'order.logistics_updated',
            'subject_type' => Order::class,
            'subject_id' => $order->id,
        ]);

        // Verify that the order has the tracking relationship and accessors work
        $order->refresh();
        $this->assertEquals('TEST-12345', $order->tracking_number);
        $this->assertEquals($courier->id, $order->shipping_courier_id);
        $this->assertEquals('DHL Express', $order->shipping_carrier);
        $this->assertEquals('https://dhl.com/track/TEST-12345', $order->tracking_url);
        $this->assertEquals('2026-07-05 00:00:00', $order->estimated_delivery_at->format('Y-m-d H:i:s'));
    }

    /**
     * Test that tracking details are auto-generated when order is Shipped with empty tracking details.
     */
    public function test_order_tracking_details_are_autogenerated_on_shipped(): void
    {
        $order = Order::create([
            'ulid' => (string) \Illuminate\Support\Str::ulid(),
            'order_number' => 'ORD-' . rand(1000, 9999),
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
            'address' => '123 Main St',
            'city' => 'New York',
            'zip' => '10001',
            'subtotal' => 100.00,
            'tax' => 10.00,
            'total' => 110.00,
            'status' => 'Processing',
        ]);

        $response = $this->actingAs($this->admin)->put(route('admin.orders.update', $order->ulid), [
            'status' => 'Shipped',
            'payment_status' => 'Paid',
            'tracking_number' => '',
            'shipping_carrier' => '',
            'tracking_url' => '',
            'estimated_delivery_at' => '',
        ]);

        $response->assertRedirect();

        $tracking = OrderTracking::where('order_id', $order->id)->first();
        $this->assertNotNull($tracking);
        $this->assertStringStartsWith('SG-TRK-', $tracking->tracking_number);
        $this->assertEquals('Delhivery Express', $tracking->shipping_carrier);
        $this->assertEquals('https://www.delhivery.com/track/package/' . $tracking->tracking_number, $tracking->tracking_url);
        $this->assertNotNull($tracking->estimated_delivery_at);
    }

    /**
     * Test that package uninstall command drops table, deletes migration record and removes published migration file.
     */
    public function test_package_uninstall_command(): void
    {
        // Explicitly register the command in the test to ensure it is resolved by the console kernel
        $this->app->make(\Illuminate\Contracts\Console\Kernel::class)->registerCommand(
            app(\SGCart\LogisticTracking\Console\Commands\UninstallCommand::class)
        );

        // 1. Create a dummy published migration file
        $dummyMigrationPath = database_path('migrations/2026_06_29_999999_create_order_trackings_table.php');
        if (!file_exists(dirname($dummyMigrationPath))) {
            mkdir(dirname($dummyMigrationPath), 0755, true);
        }
        file_put_contents($dummyMigrationPath, '<?php return new class extends \Illuminate\Database\Migrations\Migration {};');

        // 2. Ensure table exists
        $this->assertTrue(\Illuminate\Support\Facades\Schema::hasTable('order_trackings'));

        // 3. Insert a dummy migration record
        \Illuminate\Support\Facades\DB::table('migrations')->insert([
            'migration' => '2026_06_29_999999_create_order_trackings_table',
            'batch' => 1,
        ]);

        // 4. Run the uninstall command
        $this->artisan('logistic-tracking:uninstall')
            ->assertExitCode(0);

        // 5. Assert table is dropped
        $this->assertFalse(\Illuminate\Support\Facades\Schema::hasTable('order_trackings'));
        $this->assertFalse(\Illuminate\Support\Facades\Schema::hasTable('shipping_couriers'));

        // 6. Assert migration record is deleted
        $this->assertDatabaseMissing('migrations', [
            'migration' => '2026_06_29_999999_create_order_trackings_table',
        ]);

        // 7. Assert published migration file is deleted
        $this->assertFileDoesNotExist($dummyMigrationPath);

        // 8. Re-run migrations to restore the table for other tests
        $this->artisan('migrate');
    }

    /**
     * Test that admin can view shipping couriers page.
     */
    public function test_admin_can_view_shipping_couriers_page(): void
    {
        $response = $this->actingAs($this->admin)->get(route('admin.couriers.index'));
        $response->assertStatus(200);
        $response->assertSee('Shipping Couriers');
    }

    /**
     * Test that admin can view create shipping courier modal text on index page.
     */
    public function test_admin_can_view_create_shipping_courier_modal_text_on_index_page(): void
    {
        $response = $this->actingAs($this->admin)->get(route('admin.couriers.index'));
        $response->assertStatus(200);
        $response->assertSee('Add Shipping Courier');
    }

    /**
     * Test that admin can add shipping courier.
     */
    public function test_admin_can_add_shipping_courier(): void
    {
        $response = $this->actingAs($this->admin)->post(route('admin.couriers.store'), [
            'name' => 'DHL Express',
            'url' => 'https://dhl.com',
            'support_email' => 'support@dhl.com',
        ]);

        $response->assertRedirect(route('admin.couriers.index'));
        $this->assertDatabaseHas('shipping_couriers', [
            'name' => 'DHL Express',
            'url' => 'https://dhl.com',
            'support_email' => 'support@dhl.com',
        ]);
    }

    /**
     * Test that admin can delete shipping courier.
     */
    public function test_admin_can_delete_shipping_courier(): void
    {
        $courier = \SGCart\LogisticTracking\Models\ShippingCourier::create([
            'name' => 'FedEx',
            'url' => 'https://fedex.com',
            'support_email' => 'support@fedex.com',
        ]);

        $response = $this->actingAs($this->admin)->delete(route('admin.couriers.destroy', $courier->id));

        $response->assertRedirect(route('admin.couriers.index'));
        $this->assertDatabaseMissing('shipping_couriers', [
            'id' => $courier->id,
        ]);
    }

    /**
     * Test that admin can view edit shipping courier modal text on index page.
     */
    public function test_admin_can_view_edit_shipping_courier_modal_text_on_index_page(): void
    {
        $response = $this->actingAs($this->admin)->get(route('admin.couriers.index'));
        $response->assertStatus(200);
        $response->assertSee('Edit Shipping Courier');
    }

    /**
     * Test that admin can update shipping courier.
     */
    public function test_admin_can_update_shipping_courier(): void
    {
        $courier = \SGCart\LogisticTracking\Models\ShippingCourier::create([
            'name' => 'FedEx',
            'url' => 'https://fedex.com',
            'support_email' => 'support@fedex.com',
        ]);

        $response = $this->actingAs($this->admin)->put(route('admin.couriers.update', $courier->id), [
            'name' => 'FedEx Updated',
            'url' => 'https://newfedex.com',
            'support_email' => 'newsupport@fedex.com',
        ]);

        $response->assertRedirect(route('admin.couriers.index'));
        $this->assertDatabaseHas('shipping_couriers', [
            'id' => $courier->id,
            'name' => 'FedEx Updated',
            'url' => 'https://newfedex.com',
            'support_email' => 'newsupport@fedex.com',
        ]);
    }

    /**
     * Test that if shipping_courier_id is null/deleted but shipping_carrier is set, the carrier name is preserved.
     */
    public function test_order_tracking_preserves_carrier_name_when_courier_is_deleted_or_null(): void
    {
        $order = Order::create([
            'ulid' => (string) \Illuminate\Support\Str::ulid(),
            'order_number' => 'ORD-' . rand(1000, 9999),
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
            'address' => '123 Main St',
            'city' => 'New York',
            'zip' => '10001',
            'subtotal' => 100.00,
            'tax' => 10.00,
            'total' => 110.00,
            'status' => 'Processing',
        ]);

        // Manually create tracking with a carrier name but null courier id (e.g. deleted)
        $order->tracking()->create([
            'tracking_number' => 'TEST-12345',
            'shipping_carrier' => 'Old Deleted Carrier',
            'tracking_url' => 'https://example.com/track',
            'estimated_delivery_at' => '2026-07-05',
        ]);

        // Submit update using the "__KEEP__" value
        $response = $this->actingAs($this->admin)->put(route('admin.orders.update', $order->ulid), [
            'status' => 'Shipped',
            'payment_status' => 'Paid',
            'tracking_number' => 'TEST-12345',
            'shipping_courier_id' => '__KEEP__',
            'tracking_url' => 'https://example.com/track',
            'estimated_delivery_at' => '2026-07-05',
        ]);

        $response->assertRedirect();
        
        // Assert the carrier name is preserved and courier id remains null
        $this->assertDatabaseHas('order_trackings', [
            'order_id' => $order->id,
            'tracking_number' => 'TEST-12345',
            'shipping_courier_id' => null,
            'shipping_carrier' => 'Old Deleted Carrier',
        ]);
    }
}
