<?php

namespace Tests\Feature;

use App\Models\Order;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use SGCart\LogisticTracking\Models\OrderTracking;
use Tests\TestCase;

class LogisticTrackingTest extends TestCase
{
    use RefreshDatabase;

    protected User $admin;

    protected function setUp(): void
    {
        parent::setUp();

        // Create an admin user for authentication
        $this->admin = User::create([
            'name' => 'Admin User',
            'email' => 'admin_' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
        ]);

        $permission = \Spatie\Permission\Models\Permission::firstOrCreate(['name' => 'manage products', 'guard_name' => 'web']);
        $this->admin->givePermissionTo($permission);
    }

    /**
     * Test that order tracking can be saved manually.
     */
    public function test_order_tracking_can_be_saved_manually(): void
    {
        $order = Order::create([
            'ulid' => (string) \Illuminate\Support\Str::ulid(),
            'order_number' => 'ORD-' . rand(1000, 9999),
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
            'address' => '123 Main St',
            'city' => 'New York',
            'zip' => '10001',
            'subtotal' => 100.00,
            'tax' => 10.00,
            'total' => 110.00,
            'status' => 'Processing',
        ]);

        $response = $this->actingAs($this->admin)->put(route('admin.orders.update', $order->ulid), [
            'status' => 'Shipped',
            'payment_status' => 'Paid',
            'tracking_number' => 'TEST-12345',
            'shipping_carrier' => 'Test Carrier',
            'tracking_url' => 'https://example.com/track/TEST-12345',
            'estimated_delivery_at' => '2026-07-05',
        ]);

        $response->assertRedirect();
        $this->assertDatabaseHas('order_trackings', [
            'order_id' => $order->id,
            'tracking_number' => 'TEST-12345',
            'shipping_carrier' => 'Test Carrier',
            'tracking_url' => 'https://example.com/track/TEST-12345',
        ]);

        $this->assertDatabaseHas('activity_log', [
            'event' => 'order.logistics_updated',
            'subject_type' => Order::class,
            'subject_id' => $order->id,
        ]);

        // Verify that the order has the tracking relationship and accessors work
        $order->refresh();
        $this->assertEquals('TEST-12345', $order->tracking_number);
        $this->assertEquals('Test Carrier', $order->shipping_carrier);
        $this->assertEquals('https://example.com/track/TEST-12345', $order->tracking_url);
        $this->assertEquals('2026-07-05 00:00:00', $order->estimated_delivery_at->format('Y-m-d H:i:s'));
    }

    /**
     * Test that tracking details are auto-generated when order is Shipped with empty tracking details.
     */
    public function test_order_tracking_details_are_autogenerated_on_shipped(): void
    {
        $order = Order::create([
            'ulid' => (string) \Illuminate\Support\Str::ulid(),
            'order_number' => 'ORD-' . rand(1000, 9999),
            'first_name' => 'John',
            'last_name' => 'Doe',
            'email' => 'john@example.com',
            'address' => '123 Main St',
            'city' => 'New York',
            'zip' => '10001',
            'subtotal' => 100.00,
            'tax' => 10.00,
            'total' => 110.00,
            'status' => 'Processing',
        ]);

        $response = $this->actingAs($this->admin)->put(route('admin.orders.update', $order->ulid), [
            'status' => 'Shipped',
            'payment_status' => 'Paid',
            'tracking_number' => '',
            'shipping_carrier' => '',
            'tracking_url' => '',
            'estimated_delivery_at' => '',
        ]);

        $response->assertRedirect();

        $tracking = OrderTracking::where('order_id', $order->id)->first();
        $this->assertNotNull($tracking);
        $this->assertStringStartsWith('SG-TRK-', $tracking->tracking_number);
        $this->assertEquals('Delhivery Express', $tracking->shipping_carrier);
        $this->assertEquals('https://www.delhivery.com/track/package/' . $tracking->tracking_number, $tracking->tracking_url);
        $this->assertNotNull($tracking->estimated_delivery_at);
    }

    /**
     * Test that package uninstall command drops table, deletes migration record and removes published migration file.
     */
    public function test_package_uninstall_command(): void
    {
        // Explicitly register the command in the test to ensure it is resolved by the console kernel
        $this->app->make(\Illuminate\Contracts\Console\Kernel::class)->registerCommand(
            app(\SGCart\LogisticTracking\Console\Commands\UninstallCommand::class)
        );

        // 1. Create a dummy published migration file
        $dummyMigrationPath = database_path('migrations/2026_06_29_999999_create_order_trackings_table.php');
        if (!file_exists(dirname($dummyMigrationPath))) {
            mkdir(dirname($dummyMigrationPath), 0755, true);
        }
        file_put_contents($dummyMigrationPath, '<?php return new class extends \Illuminate\Database\Migrations\Migration {};');

        // 2. Ensure table exists
        $this->assertTrue(\Illuminate\Support\Facades\Schema::hasTable('order_trackings'));

        // 3. Insert a dummy migration record
        \Illuminate\Support\Facades\DB::table('migrations')->insert([
            'migration' => '2026_06_29_999999_create_order_trackings_table',
            'batch' => 1,
        ]);

        // 4. Run the uninstall command
        $this->artisan('logistic-tracking:uninstall')
            ->assertExitCode(0);

        // 5. Assert table is dropped
        $this->assertFalse(\Illuminate\Support\Facades\Schema::hasTable('order_trackings'));

        // 6. Assert migration record is deleted
        $this->assertDatabaseMissing('migrations', [
            'migration' => '2026_06_29_999999_create_order_trackings_table',
        ]);

        // 7. Assert published migration file is deleted
        $this->assertFileDoesNotExist($dummyMigrationPath);

        // 8. Re-run migrations to restore the table for other tests
        $this->artisan('migrate');
    }
}
